### ISSUE TITLE
Query regarding limite of four classes of Service 

### ISSUE THREAD

**Issue by MohdAhmad** [01org/intel-cmt-cat#1]
Is the limit of `4` classes of service (COS) on the `Intel(R) Xeon(R) processor E5 v3 generation` permanent or it limited by the current software implementation and will expand in the future. I ask because the section `17.16.3.3 Cache Mask Configuration` of the Intel Software Developer's manuals mentions that the range of MSRs reserved for CAT can accommodate up to `256` COS or multiple resources.

**Comment by tkanteck** [comment]
Number of classes of service is product dependent and for Intel(R) Xeon(R) processor E5 v3 product family, the number is 4. There are 256 MSR addresses reserved for the classes of service.

**Comment by tkanteck** [comment]
MohdAhmad, I hope my comment explains difference between MSR address space described in Intel Software Developer's manual and actual number of classes of service implemented in Intel(R) Xeon(R) E5 v3 processors. If you have more questions then I'll be happy to answer them. I am going to close this issue for now.
