### ISSUE TITLE
make clean not cleaning lib directory

### ISSUE THREAD

**Issue by ColinIanKing** [01org/intel-cmt-cat#10]
$ make clean
$ ls lib/*.[ao] 
lib/cpuinfo.o	       lib/host_cap.o	      lib/host_pidapi.o  lib/log.o	lib/utils.o
lib/host_allocation.o  lib/host_monitoring.o  lib/libpqos.a	 lib/machine.o

**Comment by tkanteck** [comment]
It was kind of intended and 'make clobber' does this lib cleaning job.
The idea was that there is no need to clean the library when cleaning the pqos application code.
Please let know if you think the above breaks user expectations.

**Comment by ColinIanKing** [comment]
OK, thanks, that clarifies things. I guess I was expecting "make clean" to really make clean like on most projects.

**Comment by tkanteck** [comment]
If it is a common practice to have 'make clean' clean everything then we can follow the same pattern. Then we could change 'make clobber' into some 'light clean' of application code only.

**Comment by ColinIanKing** [comment]
I think that would be helpful. I got caught out with a i386 build when I did "make clean" from a previous x86-64 build and I had weird linker issues untilI figured out make clean didn't clean the lib directory. So I personally think "make clean" should clean up everything so there are no surprises.  If that's OK with you.

**Comment by tkanteck** [comment]
OK - it makes sense. I'll have a look into it.

**Comment by tkanteck** [comment]
Done.
'clean' - cleans everything
'rinse' - light clean of local build files

**Comment by ColinIanKing** [comment]
Thanks! Much appreciated.
