### ISSUE TITLE
Do core base L3 allocations extend to kernel/ring0 code?

### ISSUE THREAD

**Issue by MohdAhmad** [01org/intel-cmt-cat#11]
Do core based limitations extend to Kernel code? So if I have a kernel module run on a particular core, will it be limited to the L3 allocation for that particular core or are the limitations just for userspace applications?

**Comment by tkanteck** [comment]
Good question. Currently, the utility and library offer static CAT configuration. This means cores are assigned to classes of service and this configuration doesn't change when tasks are scheduled in and out on this core. Consequently linux kernel threads running on this core will be also affected. Depending on the application it may be a good or a bad thing. There is work in progress to enable CAT configuration on task basis to address this gap.

**Comment by MohdAhmad** [comment]
@tkanteck Thanks for clarifying!
