### ISSUE TITLE
use of ncurses rather than ANSI escape sequences to produce tty output

### ISSUE THREAD

**Issue by ColinIanKing** [01org/intel-cmt-cat#12]
Using ANSI escape sequences works on a limited subset of terminals.  It may be a good idea to use ncurses instead for a couple of reasons:

1, it is more efficient over slow tty serial connections
2, it supports more ttys
3, it is less flickery
4, it will restore the screen when complete

Just a wish really, and would make the tool look more polished.

**Comment by tkanteck** [comment]
Thanks for the suggestion! I'll add it to out backlog. We need to check effort behind this activity and license compatibility.

**Comment by tkanteck** [comment]
Hi Colin,
This is more than 6 months since the issue has been logged. It is in our backlog and it is at the bottom of our TODO list :( We may have another look at it later this year.
Let me close this issue for now. If you disagree then feel free to re-open.
