### ISSUE TITLE
does the cache partion can dynamic change?

### ISSUE THREAD

**Issue by pangbingqiang** [01org/intel-cmt-cat#14]
Hi,thanks for you answer. It is my first time to use CAT may have some simple question:
  1. does the cache partion can dynamic change?
  2. does the CAT must have the kernel support,  whetner it can directly use by r/w msrs?
  3.https://lkml.org/lkml/2015/6/25/591 list the kernel support the cat ,it is can use now, which kernel version?

**Comment by tkanteck** [comment]
Sure, no problem:
1. yes it can
2. the tool & library were initially created to use MSR registers. So it will work on legacy kernels as long as there is MSR kernel driver available. The downside of MSR interface is that the technologies can be managed on logical core basis only - no task or process tracking capability.
Going forward, as these technologies get adopted into upstream kernel the tool will be extended to support kernel interfaces, too. See PID monitoring option.
3. Latest known to me status of the patchset you refer to is that it not upstream yet

Just a final note on the topic:
- mixed use of MSR and kernel interfaces to manage CAT or CMT & MBM may lead to unexpected behavior

I hope it helps.

**Comment by pangbingqiang** [comment]
thanks~
