### ISSUE TITLE
Null pointer deference in parse_allocation_cos(), alloc.c

### ISSUE THREAD

**Issue by ColinIanKing** [01org/intel-cmt-cat#15]
a parse_error is reported on detection of a NULL, but then immediately afterwards a zero char is written to the NULL pointer, which will cause a segfault. 

        p = strchr(str, '=');
        if (p == NULL)
                parse_error(str, "invalid class of service definition");
        *p = '\0';

**Comment by ColinIanKing** [comment]
And same in parse_allocation_assoc() too:

        if (p == NULL)
                parse_error(str,
                            "Invalid allocation class of service "
                            "association format");
        *p = '\0';

**Comment by tkanteck** [comment]
This would be a serious problem if parse_error() was returning control to the caller. However current implementation never returns (see below). It prints the messages and exits:

__attribute__ ((noreturn)) void
parse_error(const char *arg, const char *note)
{
        printf("Error parsing \"%s\" command line argument. %s\n",
               arg ? arg : "<null>",
               note ? note : "");
        exit(EXIT_FAILURE);
}

I admit this is not very elegant and should be improved in the future. Yet it simplifies error handling when parsing inputs strings.

Thanks for being vigilant!

**Comment by ColinIanKing** [comment]
On 05/02/16 10:31, Tomasz Kantecki wrote:
> This would be a serious problem if parse_error() was returning control
> to the caller. However current implementation never returns (see below).
> It prints the messages and exits:
> 
> *attribute* ((noreturn)) void
> parse_error(const char *arg, const char *note)
> {
> printf("Error parsing \"%s\" command line argument. %s\n",
> arg ? arg : "",
> note ? note : "");
> exit(EXIT_FAILURE);
> }

Oops, I overlooked that. Doh.
