### ISSUE TITLE
Intel Resource Director Technology and Intel Performance Counter Monitor

### ISSUE THREAD

**Issue by xzhangxin** [01org/intel-cmt-cat#27]
Hello,
I'm interested about whether I could use Intel Resource Director Technology and Intel Performance Counter Monitor together. I'd like to monitor some resources, which are only separately available in one of them. But both of them will access to the model-specific register (MSR), it may lead to interfere. Should they run parallel to each other or not?

**Comment by tkanteck** [comment]
Hello,
Thanks for the contact. Unfortunately, these two tools cannot run in parallel due to the reasons described above: access to MSR registers and RMID's. It is not safe to run Intel PCM or pqos with Linux perf CMT & MBM events at the same time either.
It is OK to run multiple instances of pqos tool for monitoring as long as monitored core sets are exclusive (don't overlap).
Could you use Linux perf only to monitor events of interest?
Thanks,
Tomasz

**Comment by tkanteck** [comment]
Let me close this issue for now. If you have any further questions please open a new one.
Thanks,
Tomasz

**Comment by tkanteck** [comment]
Just a comment clarifying today situation:

There are about three different tools that provide MBM and CMT monitoring capability at the moment:
- Linux perf (CMT kernel 4.1+, MBM kernel 4.6+)
- Intel PCM
- pqos (intel-cmt-cat)
As of today, Intel PCM and pqos access MSR registers from user space to monitor CMT/MBM. 'pqos' can detect that Intel PCM is running and will not start monitoring of the same cores.
When pqos and Intel PCM transition to use perf interface for CMT/MBM then use of the tools in parallel will be completely safe.

**Comment by xzhangxin** [comment]
Thanks for the reply. I'd like to use Intel PCM and pqos together, because Intel PCM could monitor more kinds of resource, and pqos could monitor the resource with different pid. Unfortunately, they can't be used at the same time. So I try to directly use Linux perf with the raw hardware event descriptor to monitor all the interested events, but it's not easy to find out all the correct event numbers and umask values, and they may be different with different processor architectures.

Now I decide to use Intel PCM and Linux perf together, while Linux perf only monitor some kvm events, which belong to the tracepoint events. Do you think it is safe?

**Comment by tkanteck** [comment]
It should be safe as long as perf doesn't monitor CMT or MBM.

**Comment by xzhangxin** [comment]
Thanks!
