### ISSUE TITLE
How fine-grained can the cache assignment be for each COS? 

### ISSUE THREAD

**Issue by MohdAhmad** [01org/intel-cmt-cat#3]
How fine-grained can the cache assignment be for each COS? Is there a limitation to how fine-grained the assignment can be, for instance, can I assign 1MB to a given COS? 

I have successfully used the sample CFG0 that equally divides the cache between all the classes of service. I am using the Intel(R) Xeon(R) CPU E5-2618L v3 @ 2.30GHz machine.

**Comment by pvautee** [comment]
Each COS should be at least assigned 2 contiguous bitmasks. i.e. 2 ways minimum for Intel (R) Xeon(R) E5 v3 processors. So for your Intel(R) Xeon(R) CPU E5-2618L v3 @ 2.30GHz, 20 MB cache, it will minimum 2 MB cache per COS needs to be assigned.

**Comment by MohdAhmad** [comment]
Thanks @pvautee for the quick response. I have a few followup questions. 

Is the minimum increment I can do on top of the 2 MB is 1 MB? To confirm, the cache partitioning is done by partitioning ways, right? Thanks for the help.

**Comment by pvautee** [comment]
Yes, you are right. 
The minimum increment you can do on top of the 2MB is 1MB. So, for example minimum bitmask = 0x00003 i.e. (2 MB) and minimum increment on top of the 0x00003 can be = 0x00007 i.e. (3 MB).

**Comment by MohdAhmad** [comment]
@pvautee Thanks!

**Comment by anastop** [comment]
> Each COS should be at least assigned 2 contiguous bitmasks
I'm reviving this issue because it seems the above rule does not apply on my machine (E5-2699 v4). 
I was able to successfully define an allocation class with a single-bit mask (`pqos -e 'llc:1=0x1'`). 
Also, `pqos -s` verifies that COS1 has this mask. 

Is this behavior expected on my machine?

**Comment by tkanteck** [comment]
The behavior for 1 bit masks is product specific and it is not guaranteed to work across all products.
