### ISSUE TITLE
Unexpected action in mask definition

### ISSUE THREAD

**Issue by yannispapadakis** [01org/intel-cmt-cat#30]
Hello to everyone!

I am experiencing the following issue with the cache allocation feature:
I am trying to define the mask of a Class of Service to be 0x80000, and another one to be 0x7FFFF, (so I am trying to achieve an isolation scheme).
`pqos -e 'llc:1=0x80000;llc:2=0x7ffff'`

However, after receiving the appropriate message of success, I see that the mask of the COS which was defined as 0x80000, is instead 0xC0000, which means that I am getting an extra way of associativity, and the isolation is not achieved. 

I inserted debug messages in the process of defining the mask, but in no point did I find an error or a change in the mask, until the call to msr_write in host_allocation.c

CPU: Intel Xeon CPU E5-2699 v4 @ 2.20GHz

**Comment by pvautee** [comment]
“Hardware OR’s in 19th bit, because that is mandatory to set bit 19 and 18.” Hence, when mask 0x80000 echoed effective way mask will be 0xC0000".  I hope that explains behavior you are seeing.

**Comment by yannispapadakis** [comment]
Thank you for your answer pvautee!
Yes, that explains the behavior! I changed the masks, and now I have the allocation that I expected!
