### ISSUE TITLE
Some question about CAT

### ISSUE THREAD

**Issue by ChaosySama** [01org/intel-cmt-cat#31]
Hi everyone !

I have some question about CAT :

1. I know the number of classes and the number of cache ways can change , but how to change them ? Is there any function to change them with pqos?

2.  I saw there are many socket and each socket has its own COS , when i change the COS MASK, all of socket have been changed, how can i only change one of them? For example: i only want to change COS1 MASK in socket 0.

Thanks for your answer !

**Comment by tkanteck** [comment]
Hi Chaos !

Thanks for reaching out with your questions.

As to question 1:
- Number of cache ways and classes of service are product specific. They cannot be changed after CPU is manufactured.
- Number of cache ways in server CPU's tends to vary between 12 and 20 ways.
- Number of classes of service can be 4, 8 (CDP on) or 16 (no CDP or CDP off).

As to question 2:
- This legitimate use case and pqos tool supports this usage model. Please have a look into this section of wiki: https://github.com/01org/intel-cmt-cat/wiki/Usage-Examples#set-cos-1-on-all-sockets-cos-2-on-socket-0-and-1-and-cos-3-on-sockets-2-to-3
- Make sure to take the latest snapshot of the code as this feature is not part of 0.1.4 release

Thanks,
Tomasz

**Comment by ChaosySama** [comment]
Thanks for your quickly answer !

**Comment by tkanteck** [comment]
You are welcome - happy to help. Let me close this issue.
Feel free to reopen it or create a new one if you have further questions.
