### ISSUE TITLE
COS out of range check needed for L3 CAT in pqos utility.

### ISSUE THREAD

**Issue by mdcornu** [01org/intel-cmt-cat#33]
Right now, when the user tries to set a L3 CAT COS with an invalid class ID using the pqos utility, the library returns an error and the application simply fails. A check should be added to the pqos utility to verify that the specified class ID is valid and if not, should print a message to the user stating so.

**Comment by ahetheri** [comment]
This patch fixes the problem [10a615b](https://github.com/01org/intel-cmt-cat/commit/10a615b168c6d9f9cf5c0333ae73c2607bab1ea6)
