### ISSUE TITLE
rdtset make all failed

### ISSUE THREAD

**Issue by anksv** [01org/intel-cmt-cat#36]
user@ubuntu:~/ankur/intel-cmt-cat/rdtset$ sudo make all
cc -MM -MP -MF rdtset.d -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3 rdtset.c
cat rdtset.d | sed 's/rdtset.o/rdtset.d/' >> rdtset.d
cc -MM -MP -MF rdt.d -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3 rdt.c
cat rdt.d | sed 's/rdt.o/rdt.d/' >> rdt.d
cc -MM -MP -MF cpu.d -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3 cpu.c
cat cpu.d | sed 's/cpu.o/cpu.d/' >> cpu.d
cc -MM -MP -MF common.d -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3 common.c
cat common.d | sed 's/common.o/common.d/' >> common.d
cc -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3   -c -o common.o common.c
cc -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3   -c -o cpu.o cpu.c
cc -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3   -c -o rdt.o rdt.c
cc -I../lib -W -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wold-style-definition -Wpointer-arith -Wcast-qual -Wundef -Wwrite-strings -Wformat -Wformat-security -fstack-protector -fPIE -D_FORTIFY_SOURCE=2 -Wunreachable-code -Wmissing-noreturn -Wsign-compare -Wno-endif-labels -D_GNU_SOURCE -Wcast-align -Wnested-externs -g -O3   -c -o rdtset.o rdtset.c
cc -L../lib -fPIE -z noexecstack -z relro -z now common.o cpu.o rdt.o rdtset.o -lpqos -lpthread -o rdtset
rdt.o: In function `alloc_release':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:862: undefined reference to `pqos_alloc_release'
rdt.o: In function `cat_set':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:1030: undefined reference to `pqos_alloc_assign'
rdt.o: In function `cat_configure_cos':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:972: undefined reference to `pqos_l2ca_set'
rdt.o: In function `alloc_release':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:862: undefined reference to `pqos_alloc_release'
rdt.o: In function `check_cpus':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:511: undefined reference to `pqos_alloc_assoc_get'
rdt.o: In function `cat_reset':
/home/xiaoning/ankur/intel-cmt-cat/rdtset/rdt.c:1101: undefined reference to `pqos_alloc_assoc_set'
collect2: error: ld returned 1 exit status
Makefile:86: recipe for target 'rdtset' failed
make: *** [rdtset] Error 1

**Comment by anksv** [comment]
user@ubuntu:~/ankur/intel-cmt-cat/rdtset$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               1200.035
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4194.75
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

**Comment by anksv** [comment]
user@ubuntu:~/ankur/intel-cmt-cat/rdtset$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

**Comment by mdcornu** [comment]
Hi Ankur, same applies here with rdtset as per my response to your pqos build issue.

Build everything from the top level directory with **cd intel-cmt-cat && make**
Or, build the library with **cd intel-cmt-cat/lib && make** and then build the rdtset tool.

The library must be built first before building the tools. You can also (optionally) install the library by running **cd intel-cmt-cat/lib && sudo make install**. Without installation, you will need to use LD_LIBRARY_PATH env variable to point to the library in **intel-cmt-cat/lib**.

**Comment by tkanteck** [comment]
Hi Ankur,
Did the above explanation fix your problem? Is it OK to close #36 (this) & #35 issues?
Thanks

**Comment by anksv** [comment]
Yes, thanks
