### ISSUE TITLE
Error initializing PQoS library on purley machine

### ISSUE THREAD

**Issue by taget** [01org/intel-cmt-cat#37]
Any kernel version requires?

Linux PLY01SDP 4.8.0-22-generic #24-Ubuntu SMP Sat Oct 8 09:15:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
(reverse-i-search)`lsc': ^Ccpu
test@PLY01SDP:~/intel-cmt-cat$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                112
On-line CPU(s) list:   0-111
Thread(s) per core:    2
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            06/55
Stepping:              2
CPU MHz:               1399.987
CPU max MHz:           3200.0000
CPU min MHz:           1000.0000
BogoMIPS:              3600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27,56-83
NUMA node1 CPU(s):     28-55,84-111

test@PLY01SDP:~/intel-cmt-cat$ pqos -m llc:0
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
WARN: Error opening file '/dev/cpu/0/msr'!
ERROR: CDP detection error!
ERROR: Fatal error encounter in L3 CAT discovery!
ERROR: discover_capabilities() error 1
Error initializing PQoS library!

**Comment by tkanteck** [comment]
No, there is no special kernel version required.
Could you make sure that MSR driver is loaded "sudo modprobe msr" and that you run pqos tool with root privilege ("sudo pqos -m llc:0") ?
From the log it looks the "test" user doesn't have rights to MSR driver files.

**Comment by taget** [comment]
@tkanteck oh, works, thanks for your quick response. I will close this.

Eli.
