### ISSUE TITLE
Assignment of COS to cores per socket

### ISSUE THREAD

**Issue by jgjl** [01org/intel-cmt-cat#38]
Hi,

I need to assign CPU cores from different sockets to their respective COS on each socket.

For example, I have theses COS:
```
pqos -e llc@1:1=0x0003E;llc@1:2=0x007C0;llc@0:1=0x0001E;llc@0:2=0x007E0
```
Now I want to assign the cores per socket (made up example):
```
pqos -a "llc@1:1=0,2,6-10;llc@0:1=1;"
```
However, the command as stated above does not work.
Any hints on how to specify which socket to use when assigning COS to cores?

Does this happen automatically depending on the location of the core?

**Comment by mdcornu** [comment]
Hi jgjl,

Cores will be associated to the COS defined on their respective socket.
Example: "pqos -a llc:1=0,2,6-10" will associate cores 0,2,6-10 to COS 1 on socket 0 (assuming all these cores are on socket 0). In your case, the effective mask would be 0x0001E.

Note: The "@" notation is only valid for the "-e" option to set the COS definition.

**Comment by jgjl** [comment]
Hi mdcornu,

thank you for the explanation!
