### ISSUE TITLE
What is meant by `number of classes = 4, number of cache ways = 12`

### ISSUE THREAD

**Issue by MohdAhmad** [01org/intel-cmt-cat#4]
`sudo ./pqos -H` returns the following. 
`
1)
      Config ID: CFG0
    Description: non-overlapping, ways equally divided
 Configurations:
	number of classes = 4, number of cache ways = 12
	number of classes = 4, number of cache ways = 16
	number of classes = 4, number of cache ways = 20`
`2)
      Config ID: CFG1
    Description: non-overlapping, ways unequally divided
 Configurations:
	number of classes = 4, number of cache ways = 12
	number of classes = 4, number of cache ways = 16
	number of classes = 4, number of cache ways = 20`
`3)
      Config ID: CFG2
    Description: overlapping, ways unequally divided, class 0 can access all ways
 Configurations:
	number of classes = 4, number of cache ways = 12
	number of classes = 4, number of cache ways = 16
	number of classes = 4, number of cache ways = 20  `
`4)
      Config ID: CFG3
    Description: ways unequally divided, overlapping access for higher classes
 Configurations:
	number of classes = 4, number of cache ways = 12
	number of classes = 4, number of cache ways = 16
	number of classes = 4, number of cache ways = 20
`

What is meant by `number of classes = 4, number of cache ways = 12
	number of classes = 4, number of cache ways = 16
	number of classes = 4, number of cache ways = 20` which is repeated across all the options?

**Comment by tkanteck** [comment]
"-H" option lists predefined CAT profiles available in the tool. Each profile has its ID, brief description and list of hardware configurations on which it can be applied on, for example:
 number of classes = X, number of cache ways = Y
- this means that profile can be applied on CPU that supports minimum X classes of service and has exactly Y cache ways. Currently, all profiles can be applied on CPU's with 12, 16 and 20 last level cache ways.

**Comment by MohdAhmad** [comment]
@tkanteck perfect. Thanks for clarifying!
