### ISSUE TITLE
Questions about info returned from pqos

### ISSUE THREAD

**Issue by anastop** [01org/intel-cmt-cat#41]
Hi, 

`pqos -sv` on my platform returns: 

```
INFO: L3 CAT details: CDP support=1, CDP on=0, #COS=16, #ways=20, ways contention bit-mask 0xc0000
```

1.  What is the "ways contention bit-mask"? 
2. Does `#ways=20` refer to the L3 associativity ways, or the _subsets_ to which L3 can be partitioned? The Intel System Programming Guide states (17.18.2): 

   > Though the representation of CBMs looks similar to a way-based mapping they are independent 
   > of any enforcement implementation (e.g. way partitioning)
   
   I understand that, on my platform, cache partitioning is performed on a way-basis, but this might be 
   different in future implementations.

**Comment by tkanteck** [comment]
Hi, thanks for reaching out to us. Please find answers below.
1) LLC access mask used by other agents (not CPU cores) in the processor package. In case of intel(R) Xeon(R) Processor that you have it can be DDIO for example.

2) The line quoted above displays cache information retrieved from cpuid. 'ways' here refers to associativity ways.
As to CBM and cache ways, today most processors implement 1-to-1 mapping between CBM bit and cache way (1 CBM bit = 1 way). You are correct in your thinking that other mappings can be applied in the future, example 1 CBM bit = 2 ways.

**Comment by anastop** [comment]
Thanks for your reply.  

So, regarding the "ways contention bit-mask", I understand that when assigning a cache partition for _dedicated_ use by an application, I should choose from all the LLC subsets apart from those corresponding to the "ways contention bit-mask". That is, `0xfffff` - `0xc0000` = `0x3ffff`. 

Is this correct?

**Comment by anastop** [comment]
That makes sense. Thanks a lot for the clarification!

**Comment by tkanteck** [comment]
Let me close this issue. Feel free to create a new one if you have further questions.
