### ISSUE TITLE
Wrong documentation about the CAT capability in Processor D

### ISSUE THREAD

**Issue by PennPanda** [01org/intel-cmt-cat#42]
According to the README in the repo., it says all Processor D processor has 16 CLOS registers.

Based on this information, we purchased an Intel SoC with Intel Xeon CPU D-1518@2.20GHz processor. We expect it to have 16 COS registers. 

However, after checking the cpuid.eax=10H, ecx=1H, we found it only has 4 COS registers and its CBM length is 12.

Could you please update the document, documenting the capabilities of each processor? 
The incorrect information causes us to waste money on the CPU that does not best suite our requirements. :( 

Thanks!

Meng

Update:
Remove the complaint about the CBM_Length which is product specific.
The CPU has 16 CLOS registers but the cpuid instruction provides the incorrect result, probably due to the BIOS defect.

**Comment by tkanteck** [comment]
To the best of our knowledge this CPU family should support 16 classes of service.

The information provided by CPUID can be affected by a BIOS defect. To rule out this option could you try to read the following MSR registers on your system?

- read CLOS0: sudo rdmsr 0xc90
- read CLOS4: sudo rdmsr 0xc94
- read CLOS8: sudo rdmsr 0xc98
- read CLOS15: sudo rdmsr 0xc9f

Please let me know the result.
Thanks,
Tomasz

**Comment by tkanteck** [comment]
CBM length is product specific and 20 can only be found on Intel(R) Xeon(R) E5 and E7 processors (v3 and v4).
Please let me know if there is fragment of the documentation that suggest Intel(R) Xeon(R) Processor D family supports CBM of size 20.
Thanks,
Tomasz

**Comment by PennPanda** [comment]
Hi Tomasz,

Thank you so much for your prompt reply! I really appreciate it.
All of the suggested sudo rdmsr commands returns the result 0xfff. So I guess it's the defect of BIOS which makes cpuid returns the wrong value. :(

As to CBM length, I see the point now. (I'm sorry that I got the wrong impression. I will modify the issue.)
But if it is product specific, how can I know the CBM length of a CPU before I purchase it?

Thanks,

Meng

**Comment by tkanteck** [comment]
Hi Meng,

Before you get BIOS update that fixes the CPUID problem you may try to apply small change in the library that will enable intel-cmt-cat software on your system.
In short, you need to make discover_alloc_l3_probe() to be used for L3 CAT detection and no other function. In order to do it, comment out the following lines in lib/cap.c (https://github.com/01org/intel-cmt-cat/blob/master/lib/cap.c):

- lines 784 to 800 (inclusive)
- line 805

Let me know if that worked.
Thanks,
Tomasz

**Comment by PennPanda** [comment]
Hi Tomasz,

I see. Which command should I run after compiling?
Can I run without installing it?

Meng

**Comment by ahetheri** [comment]
Hi Meng

Yes you can run without re-installing.
in the /intel-cmt-cat dir please use:

sudo LD_LIBRARY_PATH=lib/ pqos/pqos -s -V

Best,
Aaron

**Comment by PennPanda** [comment]
Hi Aaron,
Thanks for the advice!

Hi Tomasz,

The result is attached at the end of the message, which is consistent with the rdmsr. 

BTW, does Intel documents the number of cache ways supported on each processor? If so, I think I know how to tell the CBM_LENGTH of a cpu before purchase the cpu. 


sudo LD_LIBRARY_PATH=lib/ pqos/pqos -s -V
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
INFO: CACHE: type 1, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 2, level 1, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 64 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 2, max id sharing this cache 2 (1 bits)
DEBUG: CACHE: not inclusive, direct mapped, 8 way(s), 512 set(s), line size 64, 1 partition(s)
INFO: CACHE: type 3, level 3, max id sharing this cache 16 (4 bits)
DEBUG: CACHE: inclusive, complex cache indexing, 12 way(s), 8192 set(s), line size 64, 1 partition(s)
DEBUG: Detected core 0, socket 0, L2 ID 0, L3 ID 0, APICID 0
DEBUG: Detected core 1, socket 0, L2 ID 1, L3 ID 0, APICID 2
DEBUG: Detected core 2, socket 0, L2 ID 2, L3 ID 0, APICID 4
DEBUG: Detected core 3, socket 0, L2 ID 3, L3 ID 0, APICID 6
DEBUG: Adding monitoring event: resource ID 1, type 1 to table index 0
DEBUG: Adding monitoring event: resource ID 1, type 4 to table index 1
DEBUG: Adding monitoring event: resource ID 1, type 2 to table index 2
DEBUG: Adding monitoring event: resource ID 1, type 8 to table index 3
DEBUG: Adding monitoring event: resource ID 0, type 32768 to table index 4
DEBUG: Adding monitoring event: resource ID 0, type 16384 to table index 5
INFO: Monitoring capability detected
INFO: CPUID.0x7.0: L3 CAT not detected. Checking brand string...
DEBUG: CPU brand string 'Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz'
WARN: Cache allocation not supported on model name 'Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz'!
ERROR: RDMSR failed for reg[0xca0] on lcore 0
INFO: L3 CAT details: CDP support=0, CDP on=0, #COS=16, #ways=12, ways contention bit-mask 0x0
INFO: L3 CAT details: cache size 6291456 bytes, way size 524288 bytes
INFO: L3CA capability detected
INFO: CPUID 0x10.0: L2 CAT not supported!
INFO: L2CA capability not detected
INFO: CPUID 0x10.0: MBA not supported!
INFO: MBA capability not detected
INFO: resctrl not detected. Kernel version 4.10 or higher required
DEBUG: Max RMID per monitoring cluster is 32
DEBUG: monitoring init OK
DEBUG: allocation init OK
L3CA COS definitions for Socket 0:
    L3CA COS0 => MASK 0xfff
    L3CA COS1 => MASK 0xfff
    L3CA COS2 => MASK 0xfff
    L3CA COS3 => MASK 0xfff
    L3CA COS4 => MASK 0xfff
    L3CA COS5 => MASK 0xfff
    L3CA COS6 => MASK 0xfff
    L3CA COS7 => MASK 0xfff
    L3CA COS8 => MASK 0xfff
    L3CA COS9 => MASK 0xfff
    L3CA COS10 => MASK 0xfff
    L3CA COS11 => MASK 0xfff
    L3CA COS12 => MASK 0xfff
    L3CA COS13 => MASK 0xfff
    L3CA COS14 => MASK 0xfff
    L3CA COS15 => MASK 0xfff
Core information for socket 0:
    Core 0, L2ID 0, L3ID 0 => COS0, RMID0
    Core 1, L2ID 1, L3ID 0 => COS1, RMID0
    Core 2, L2ID 2, L3ID 0 => COS2, RMID0
    Core 3, L2ID 3, L3ID 0 => COS3, RMID0

**Comment by tkanteck** [comment]
Hi Meng,

It seems the patch did the job and you can keep using intel-cmt-cat package while waiting for the BIOS update.

Sorry but I don't know where to find CBM size or cache ways information in the documentation.
Perhaps this data is included somewhere on ark.intel.com

Thanks
Tomasz

**Comment by PennPanda** [comment]
Thank you very much! 
I think then the issue can be closed. :)

Meng

**Comment by diksha11s** [comment]
Hi,
I am new to assembly coding. How do we check the cpuid.eax=10H, ecx=1H?Like what do I have to write in the program? I tried but it looks like I am headed in the wrong direction. Any help would be appreciated.

**Comment by mdcornu** [comment]
Hi,

Have a look at [our lcpuid function](https://github.com/intel/intel-cmt-cat/blob/c528e33ed5494cae323d9fabcfcd1355bc25a563/lib/machine.c#L115) in lib/machine.c as a reference.
Hope that helps.

Regards,
Marcel
