### ISSUE TITLE
resctrl wiki: Add note regarding build option CONFIG_INTEL_RDT_A

### ISSUE THREAD

**Issue by jbreitbart** [01org/intel-cmt-cat#43]
I was just trying to use resctrl and it took me a while to realize that there is a kernel option that has to be set (CONFIG_INTEL_RDT_A). You may want to update your wiki page and add that information. :smile:

**Comment by mdcornu** [comment]
Hi jbreitbart, you are right. This is useful info that can be added it to the wiki page.
Thanks for the feedback.

**Comment by ahetheri** [comment]
Hi jbreitbart,

Once again, thanks for the feedback. This is very useful.
We just have some questions about the environment you were using.
Can you tell us the kernel version and OS you were installing please?

Best,
Aaron

**Comment by jbreitbart** [comment]
I was using
```
$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```
and build my own kernel based on the 4.10 release.

-Jens

**Comment by ahetheri** [comment]
Hi Jens,

Thanks once again for spotting this,
The correct information has now been added to the wiki.

Please let us know if their is anything else we can update/help with,
For now, I will close this issue.

Best,
Aaron
