### ISSUE TITLE
Using CAT with Cluster on Die (COD) configuration

### ISSUE THREAD

**Issue by jgjl** [01org/intel-cmt-cat#46]
We investigated CAT on a server with Cluster on Die configuration. The results where surprising in that assigning half the cache of a Xeon E5 v4 with 32MB LLC to one class resulted in this class using only 8 MB of cache instead of 15 MB without CAT.

From the documentation it seemed that there are no special provisions required when using CAT with CoD, or am I missing something?

```
Core information for socket 0:
    Core 0 => COS3, RMID0
    Core 1 => COS3, RMID0
    Core 2 => COS1, RMID0
    Core 3 => COS2, RMID0
    Core 4 => COS2, RMID0
    Core 5 => COS2, RMID0
    Core 12 => COS1, RMID0
    Core 13 => COS1, RMID0
    Core 14 => COS1, RMID0
    Core 15 => COS2, RMID0
    Core 16 => COS2, RMID0
    Core 17 => COS2, RMID0
Core information for socket 1:
    Core 6 => COS1, RMID0
    Core 7 => COS1, RMID0
    Core 8 => COS1, RMID0
    Core 9 => COS2, RMID0
    Core 10 => COS2, RMID0
    Core 11 => COS2, RMID0
    Core 18 => COS1, RMID0
    Core 19 => COS1, RMID0
    Core 20 => COS1, RMID0
    Core 21 => COS2, RMID0
    Core 22 => COS2, RMID0
    Core 23 => COS2, RMID0
```

```
numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1 2 12 13 14
node 1 cpus: 3 4 5 15 16 17
node 2 cpus: 6 7 8 18 19 20
node 3 cpus: 9 10 11 21 22 23
[...]
```

**Comment by mdcornu** [comment]
Hi Jeremias,

Thanks for contacting us.

When CoD is enabled, LLC is logically split in half (~16MB on each cluster on your CPU). LLC of each cluster retains the same number of cache ways (bits in the contention mask) as with CoD disabled.
Your class mask is then effective on a per cluster basis, leaving you with 8MB for half of LLC on 1 cluster.

One thing to note, there is only one set of Class of Service registers that are shared across all clusters on a socket and cores can only fill into LLC on their local cluster. 
So for example, with CoD enabled on your CPU, cores 0 and 3 are on separate clusters. Despite using the same COS, for example COS1, the cores are effectively isolated and they will fill into different parts of LLC.
If you could provide more context on your CoD & RDT use case then we could advise on the best setup for you.

Note: The kernel implementation of CAT (resctrl) does not support CoD so using this interface may lead to ambiguous results.

Regards,
Marcel

**Comment by jgjl** [comment]
Hi Marcel,

thank you for your quick and helpful reply and the delay of mine.

That behavior makes sense. I will test it and come back to you. 

Right now we are using the Intel RDT tool, so the resctrl issues do not effect us.

Regards,

Jeremias

**Comment by mdcornu** [comment]
No problem Jeremias.
I'll close this issue for now, if you find any other issues are have questions feel free to reopen this or create a new issue.

Regards,
Marcel
