### ISSUE TITLE
cpus file looks strange?

### ISSUE THREAD

**Issue by jbreitbart** [01org/intel-cmt-cat#49]
According to https://github.com/01org/intel-cmt-cat/wiki/resctrl reading the cpus file should look something like:
```
# cat cpu
	c
# cat COS1/cpu
	3
```

On my system however the output is something like:
```
$ cat /sys/fs/resctrl/cpus 
ffff,e98a2f85
$ cat /sys/fs/resctrl/cobench0/cpus 
0000,00248008
$ cat /sys/fs/resctrl/cobench1/cpus 
0000,16515072
```
it is a two socket NUMA system. Do you have any idea how to interpret the cpu files? Are the two NUMA domain separated by `,`? Why is the second mask to much bigger?

Some system info:
```
$ cat /proc/cpuinfo | grep "model name" | uniq
model name	: Intel(R) Xeon(R) CPU E5-2658 v3 @ 2.20GHz

$ uname -a
Linux 4.10.0+ #1 SMP Tue Apr 11 16:03:07 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
```

CC: @stlankes @spickartz

**Comment by mdcornu** [comment]
Hi jbreitbart,

Thanks for contacting us.

The cpus file contains a bitmap (in hex) of all the cpus on the system with core 0 being the LSB in the bitmap. In your case this is 48 bits (48 cpus) which looks like this:
```
Core:     47.......................................76543210
----------------------------------------------------------
Default:   111111111111111111101001100010100010111110000101 (ffff,e98a2f85)
cobench0:  000000000000000000000000001001001000000000001000 (0000,00248008)
cobench1:  000000000000000000010110010100010101000001110010 (0000,16515072)
```
Each resctrl directory cpus file maintains a bitmap of all cpus associated to the group.
This file is not NUMA aware, the `,` is just used as a separator every 8 hex characters.

If you have any other questions, please let us know.

Regards,
Marcel

**Comment by mdcornu** [comment]
Also, you are right about the wiki. This was written based on an early version of the resctrl framework and should be updated to reflect the latest implementation.

We will update this doc soon.

Regards,
Marcel

**Comment by jbreitbart** [comment]
Thanks for the explanation.

**Comment by mdcornu** [comment]
No problem. I'll close this issue.
If you have any other questions feel free to reopen or create another issue.

Regards,
Marcel
