### ISSUE TITLE
Hardware abstraction layer for testing

### ISSUE THREAD

**Issue by AaronH88** [01org/intel-cmt-cat#54]
Hi Team,

Do you have a hardware abstraction layer available to release for testing?
I wish to try a few patches on hardware I dont have access to.

Best,
Aaron

**Comment by mdcornu** [comment]
Hi Aaron,

Apologies for the delayed response.
Currently we have a hardware abstraction layer for internal testing but this would require some time and effort before we could release it.

However, this is something we may to do in the future so I will inform you if we plan to release this code.

**_Best_**,
Marcel

**Comment by AaronH88** [comment]
Thanks for the reply, ill close this issue
