### ISSUE TITLE
Question about CBM length and minimum number of cache partitions supported

### ISSUE THREAD

**Issue by PennPanda** [01org/intel-cmt-cat#55]
Hi,

In the README, it only says the number of CLOS registers.
I'm wondering if there is any document that tells the length of the CBM field in CLOS registers on the following processors:
1) Intel Xeon Processor E5-4620 v4
2) Intel Xeon D-1518
3) Intel Xeon Processor E5-2683 v4

I remembered that the minimum number of cache partitions for a core is at least 2 for the Haswell processors. 
Does this constraint exist for any of the above three processors?

I want to confirm the CAT properties of these processors before buy any of them.
BTW, it will be really really helpful if there is a document about the details of each processor's CAT and CMT capability, such as the CBM length.

Thank you very much!

Meng

**Comment by mdcornu** [comment]
Hi Meng,

Apologies for the delayed response.

Unfortunately this information is not currently documented. 
For all the above processors there is a 1:1 mapping between CBM bits and cache ways (although this may not always be the case).

Intel Xeon Processor E5-4620 v4 / E5-2683 v4 - **20 CBM bits** (20 cache ways)
Intel Xeon D-1518 - **12 CBM bits** (12 ways)

The minimum number of cache partitions for a core on Broadwell is 1, so it will accept a single bit CBM.

Please let me know if you have any other questions.

Regards,
Marcel

**Comment by PennPanda** [comment]
Hi Marcel,

May I know the number of CBM bits for the Intel® Xeon® Processor D-1528?
I forgot to include this processor.

BTW, is there any document about the number of cache ways for each (broadwell) processor?

Thank you very much!

**Comment by mdcornu** [comment]
Hi Meng,

Unfortunately I am not aware of any documentation that has this information.
We have a Xeon D-1541 in our lab and it has 12 CBM bits. I would expect the D-1528 CPU to have the same.

Regards,
Marcel
