### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by JustPlay** [01org/intel-cmt-cat#56]
enum pqos_mon_event {
        PQOS_MON_EVENT_L3_OCCUP = 1,    /**< LLC occupancy event */
        PQOS_MON_EVENT_LMEM_BW = 2,     /**< Local memory bandwidth */
        PQOS_MON_EVENT_TMEM_BW = 4,     /**< Total memory bandwidth */
        PQOS_MON_EVENT_RMEM_BW = 8,     /**< Remote memory bandwidth
                                           (virtual event) */

maybe PQOS_MON_EVENT_LMEM_BW should equal 0x4 based on Intel manual

**Comment by mdcornu** [comment]
Hi,

Thanks for suggestion.
These enums are just ID's used to identify monitoring events in the library and tools and are not used to program MSR's. They are passed to the [get_event_id()](https://github.com/01org/intel-cmt-cat/blob/6de821a807ca767601afb28b3c10608be26089b6/lib/monitoring.c#L1150) function that returns the actual Event ID that will be used to program the counters.

The event ID's can be found in "**Table 17-18. Monitoring Supported Event IDs**" in the SW Dev Manual.

Regards,
Marcel

**Comment by JustPlay** [comment]
Hi Marcel,

L3 Local External Bandwidth's Event ID is "03H" in "Table 17-18. Monitoring Supported Event IDs" and so does in you program (get_event_id()); But the L3 Local BW's bit-position in the Event Bit Vector(CPUID.(EAX=0FH, ECX=1H).EDX) is "2"; So what is the relationship between the Event‘s ID and the bit-position in CPUID.(EAX=0FH, ECX=1H).EDX?

**Comment by tkanteck** [comment]
As Marcel explained there is no relationship between "enum pqos_mon_event" and bit positions for MBM& CMT described in SDM

**Comment by tkanteck** [comment]
Let me close this issue.
Feel free to reopen if you find a genuine problem with programming the events.
