### ISSUE TITLE
Thread-level Monitoring

### ISSUE THREAD

**Issue by narru19** [01org/intel-cmt-cat#57]
Hi!

Does the API currently support thread-level monitoring? I cannot find any documentation on it.

I've searched through the documentation on header files and an official document from [Intel's website](https://software.intel.com/sites/default/files/managed/7c/f1/253669-sdm-vol-3b.pdf), and found out that a part of the API allows both **CORE**-level or **SMT**-level monitoring.
I found this in **lib/cupinfo.c**, on the _"detect_apic_core_masks"_  function

I was also wondering if I can use the OS mode monitoring with thread ids (TID) instead of process ids (PID). A working example from the usage examples would be: _./monitoring_app -I -p threadId1_...

Thanks,

Toni

**Comment by mdcornu** [comment]
Hi Toni,

Thanks for contacting us with you're question.

Yes, the library & utility support monitoring on a per task basis as long as you are on Linux kernel 4.10+.
Example command: `pqos -I -p all:<TID1,TID2,TIDN...>`

If you have any other questions, feel free to contact us again.

Regards,
Marcel

**Comment by narru19** [comment]
Hi Marcel,

Thanks for the quick response! I am trying to integrate it into my own example. Would it be possible then to associate classes of service (CLOS) to threads in order to monitor them?

It would be basically replicating what the "monitor_app.c" example does but on a thread basis

Thanks again,

Toni

**Comment by mdcornu** [comment]
Just to clarify, classes (CLOS) are used only for allocation purposes not for monitoring.
E.g. You could modify the TID's associated CLOS to restrict it's cache resources and monitor to see the effect.

Regards,
Marcel

**Comment by narru19** [comment]
Hi Marcel,

I see, CLOS don't come into monitoring then, my bad. What I'm trying to do is, from an example program (not command line) monitor statistics such as memory bandwidth or LLC usage in a per-thread basis. Is that possible?

Regards,
Toni

**Comment by mdcornu** [comment]
Yes, as long as you are using Linux kernel 4.10 or above. When you initialize the library, make sure the [interface](https://github.com/01org/intel-cmt-cat/blob/6de821a807ca767601afb28b3c10608be26089b6/lib/pqos.h#L127) flag is set to PQOS_INTER_OS and use the [pqos_mon_start_pid()](https://github.com/01org/intel-cmt-cat/blob/6de821a807ca767601afb28b3c10608be26089b6/lib/pqos.h#L470) API to start monitoring events for the specified PID/TIDs.

Regards,
Marcel

**Comment by narru19** [comment]
Alright, thanks a lot for the quick responses! 

Regards,
Toni
