### ISSUE TITLE
Bandwidth Measurement and time interval

### ISSUE THREAD

**Issue by DemyG** [01org/intel-cmt-cat#58]
Hi everyone,

I am trying to figure out how the MBL is reported by pqos while the time interval changes. For example pqos reports the average value calculated in this interval or the max value detected ? To be more specific, what kind of measurements do I expect when time interval is for example 1 (which means, that pqos reports the monitoring values every 100ms) and when time interval is 5 (500ms). In the latter case (500ms), the repoted values are the same if I did 5 measurements with time interval 1 and then calculated the average value?

In /lib/monitoring.c function pqos_core_poll seems to have the answer. The num_poll_ctx, which is the number of poll contexes, indicates that the reported value of MBL is derived by polling and reading the MSRs ?

Thank you in advance,
Dimitra Giantsidi

**Comment by mdcornu** [comment]
HI Dimitra,

The pqos utility will always report MBL in MB/s.
The utility will scale the reported B/W up or down to reflect a 1 second interval.

E.g:
50MB/500ms would be scaled up and reported as 100MB/s.
50MB/2s would be scaled down and reported at 25MB/s.

Refer to the [code ](https://github.com/01org/intel-cmt-cat/blob/6de821a807ca767601afb28b3c10608be26089b6/pqos/monitor.c#L1324)to see how this is done.

The -i option is used to adjust monitoring granularity.

Regards,
Marcel

**Comment by DemyG** [comment]
Thank you very much for the quick and detailed answer,

Dimitra

**Comment by mdcornu** [comment]
No problem. If you have any other questions fee free to create another issue.

Regards,
Marcel
