### ISSUE TITLE
Error: "Monitoring start error on core(s) �D, status 2"

### ISSUE THREAD

**Issue by DemyG** [01org/intel-cmt-cat#60]
Hello again,

I have done some develloping in order to manage dynamically CAT but by mistake I deleted all files... Fortunately I had a previous copy which I am trying to use but while the command line instructions play (for example ./pqos -m:1-9 shows the everything) when I am pressing Ctr+C I am getting this error (  "Monitoring start error on core(s) �D, status 2"). In monitor.c it says that this error maybe is because two instances of PQoS attempt to use the same core id. I am deleting libpqos in /var/lock but nothing seems to be fixed. Also to mention that when I am trying to store results in a .csv file, the .csv is empty (nothing is stored).
How could I fix this ?

Thank you very much in advance,
Dimitra

**Comment by AaronH88** [comment]
Hi Demy,

PQoS still has a lock on the RMID's , hence the error.

You need to run the reset command, "pqos -R"
Or if your doing dev yourself with the library it is the "pqos_mon_reset(void);" function found in pqos.h

Hope this helps.

Best,
Aaron

**Comment by DemyG** [comment]
Hi Aaron,

Thank you so much. It helped a lot. I found the bug which caused this mess and which I 've never noticed before.
Thanks a lot again,
Demy
