### ISSUE TITLE
Bit masks for different cache sizes

### ISSUE THREAD

**Issue by MohdAhmad** [01org/intel-cmt-cat#7]
Can you please explain how are the bitmasks for the different cache sizes determined? 

I want to vary the size of a partition from 2MB all the way to 15MB in increments of 1MB but can't seem to figure out what the bitmasks would be for each cache size. Thanks!

**Comment by MohdAhmad** [comment]
Hey. I realized this is straightforward. Thanks.

**Comment by tkanteck** [comment]
One bit in class of service corresponds to one cache way. Cache way size can be calculated manually (total LLC size divided by number of ways).
This information can also be retrieved from the utility. Run "sudo ./pqos -s -v" and look for the following lines:
...
INFO: LLC cache size 36700160 bytes, 20 ways
INFO: LLC cache way size 1835008 bytes
...
Note that these lines will only be logged if CAT support is detected.
