### ISSUE TITLE
i386 build produces build warning because of 32 bit shift on off_t

### ISSUE THREAD

**Issue by ColinIanKing** [01org/intel-cmt-cat#9]
off_t on 32 bit i386 build is 32 bits, so  << shift of 32 bits is causing a warning.

machine.c: In function 'cpuid':
machine.c:115:57: warning: left shift count >= width of type [-Wshift-count-overflow]
         off_t offset = ((off_t)leaf) + ((off_t) subleaf << 32);

**Comment by tkanteck** [comment]
Thanks for signalling this problem and we'll surely fix it. At the moment, using lseek64() + read() looks like most portable solution to this problem.
Despite the warning, code should work fine on 32bit system as we ditched use of cpuid() in favor of lcpuid() at some stage in the past.

**Comment by tkanteck** [comment]
I hope recent changes to machine.c and machine.h resolve 32 bit build issues.
Thanks again for reporting this problem.

**Comment by ColinIanKing** [comment]
Thanks!
